export const USER_ROLES = {
	ESTUDIANTE: "Estudiante",
	PROFESOR: "Profesor",
	ADMINISTRADOR: "Administrador"
};

export const CARRERAS = [
	"Carrera Libre",
        "Administración",
        "Administración con énfasis en Gestión Financiera",
        "Administración Educativa",
        "Antropología",
        "Archivística",
        "Arte",
        "Bibliotecología",
        "Bibliotecología y Documentación",
        "Biología",
        "Biología Marina",
        "Cartografía",
        "Ciencias Actuariales",
        "Ciencias Agrarias",
        "Ciencias Ambientales",
        "Ciencias de la Educación",
        "Ciencias de la Educación con énfasis en Educación Rural",
        "Ciencias del Deporte",
        "Ciencias Forestales",
        "Ciencias Geográficas",
        "Ciencias Geográficas con énfasis en Ordenamiento Territorial",
        "Ciencias Marinas y Costeras",
        "Ciencias Políticas",
        "Comunicación",
        "Contaduría Pública",
        "Cooperativismo",
        "Danza",
        "Desarrollo Comunitario Sustentable",
        "Desarrollo Humano",
        "Desarrollo Rural",
        "Economía",
        "Educación de Adultos",
        "Educación Especial",
        "Educación Física",
        "Educación Rural",
        "Enfermería",
        "Enseñanza de la Filosofía",
        "Enseñanza de la Música",
        "Enseñanza de las Artes Plásticas",
        "Enseñanza de las Ciencias Naturales",
        "Enseñanza de las Matemáticas",
        "Enseñanza de los Estudios Sociales",
        "Enseñanza del Castellano y Literatura",
        "Enseñanza del Francés",
        "Enseñanza del Inglés",
        "Enseñanza del Inglés para III Ciclo y Educación Diversificada",
        "Estudios Interdisciplinarios",
        "Filosofía",
        "Física",
        "Francés",
        "Gestión Ambiental",
        "Gestión de la Información",
        "Gestión de Recursos Humanos",
        "Gestión de Recursos Naturales",
        "Gestión Empresarial del Turismo Sostenible",
        "Historia",
        "Ingeniería Agronómica",
        "Ingeniería en Biotecnología",
        "Ingeniería en Ciencias Forestales",
        "Ingeniería en Sistemas de Información",
        "Ingeniería Hidrológica",
        "Ingeniería Industrial",
        "Ingeniería Informática",
        "Literatura y Lingüística",
        "Manejo de Recursos Naturales",
        "Matemática",
        "Medicina",
        "Medicina Veterinaria",
        "Meteorología",
        "Música",
        "Nutrición Humana",
        "Orientación",
        "Pedagogía con énfasis en Educación Preescolar",
        "Pedagogía con énfasis en I y II Ciclos",
        "Planificación Económica y Social",
        "Producción Audiovisual",
        "Promoción de la Salud",
        "Psicología",
        "Química",
        "Relaciones Internacionales",
        "Salud Ocupacional",
        "Sociología",
        "Teatro",
        "Tecnología Educativa",
        "Tecnologías de Información",
        "Tecnologías en Salud",
        "Terapia Física",
        "Topografía",
        "Trabajo Social",
        "Traducción Francés-Español",
        "Traducción Inglés-Español",
        "Turismo"
];

export const USER_STATUS = {
	ACTIVE: "Activo",
	INACTIVE: "Inactivo",
	PENDING_VERIFICATION: "Pendiente verificación"
};

export const FORM_VALIDATION = {
	MIN_PASSWORD_LENGTH: 6,
	REQUIRED_FIELDS: [
		'nombre',
		'apellido1',
		'identificacion',
		'rol',
		'carrera',
		'correo',
		'contrasena'
	]
};

export const API_ENDPOINTS = {
	GET_ALL_USERS: "GetTodosLosUsuarios",
	ADD_USER: "AddUsuario",
	UPDATE_USER: "UpdateUsuario",
	DELETE_USER: "DeleteUsuario",
	TOGGLE_USER_STATUS: "ToggleUserStatus"
};